service:
  KIND: producer
  health_check_endpoint: http://feature-api:8000/health
  endpoint: http://feature-api:8000/predict  # localhost -> http://localhost:8000/predict, Docker -> http://feature-api:8000/predict
  input:
    KIND: parquet
    path: "data/prod/inputs_prod.parquet"  # simulate real data coming in
    storage_options: null  # can set if reading from AWS
