service:
  KIND: producer
  topic: raw_transactions
  servers: [broker:29092]  # localhost:9092 - local debugging, broker:29092 - Docker
  input:
    KIND: parquet
    path: "data/prod/prod.parquet"  # simulate real data coming in
    storage_options: null  # can set if reading from AWS
