name: fraudsys
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - zookeeper
      - broker
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  feature-producer:
    container_name: feature-producer
    restart: always
    build:
      context: .
      dockerfile: .docker/producer.Dockerfile
    depends_on:
      - broker
      - redis
    environment:
      - KAGGLE_KEY=${KAGGLE_KEY}
      - KAGGLE_USERNAME=${KAGGLE_USERNAME}
    volumes:
      - ./data/prod:/app/data/prod:ro  # :ro for read-only

  feature-cleaner:
    container_name: feature-cleaner
    restart: always
    build:
      context: .
      dockerfile: .docker/cleaner.Dockerfile
    depends_on:
      - broker
      - redis
      - feature-producer
    environment:
      - KAGGLE_KEY=${KAGGLE_KEY}
      - KAGGLE_USERNAME=${KAGGLE_USERNAME}

  feature-api:
    container_name: feature-api
    restart: always
    build:
      context: .
      dockerfile: .docker/api.Dockerfile
    depends_on:
      - broker
      - redis
      - feature-producer
    environment:
      - KAGGLE_KEY=${KAGGLE_KEY}
      - KAGGLE_USERNAME=${KAGGLE_USERNAME}
