job:
  KIND: training
  inputs:
    KIND: parquet
    path: data/training/inputs_train.parquet
    dataframe_type: pandas
  targets:
    KIND: parquet
    path: data/training/targets_train.parquet
    dataframe_type: pandas
  splitter:
    KIND: time_series
  model:
    KIND: xgboost
    subsample: 0.8
    scale_pos_weight: 10
    reg_lambda: 50
    reg_alpha: 1
    n_estimators: 500
    min_child_weight: 10
    max_depth: 7
    max_delta_step: 10
    learning_rate: 0.01
    gamma: 0
    colsample_bytree: 0.9
  metrics:
    - KIND: sklearn
  saver:
    KIND: custom_saver
  signer:
    KIND: infer_signer
  registry:
    KIND: mlflow_register
