job:
  KIND: tuning
  inputs:
    KIND: parquet
    path: data/training/inputs_train.parquet
  targets:
    KIND: parquet
    path: data/training/targets_train.parquet
  model:
    KIND: xgboost
  splitter:
    KIND: time_series
  searcher:
    KIND: random_cv
    n_iter: 5
    n_jobs: -1  # search in parallel
    param_dist: {
      n_estimators: [500, 800, 1000, 1500],
      max_depth: [4, 5, 6, 7, 8],
      learning_rate: [0.01, 0.05, 0.1, 0.15],
      subsample: [0.6, 0.7, 0.8, 0.9],
      colsample_bytree: [0.6, 0.7, 0.8, 0.9],
      reg_alpha: [0.1, 1, 5, 10, 50],
      reg_lambda: [0.1, 1, 5, 10, 50],
      min_child_weight: [1, 3, 5, 10, 15],
      gamma: [0, 0.1, 0.5, 1, 2, 5],
      scale_pos_weight: [5, 10, 20, 50, 100],
      max_delta_step: [0, 1, 5, 10]
    }
